/**
 * Runs before every test file. Nothing a developer has exported in their shell may reach a test run:
 * no real SMS, no paid AI calls, no file database.
 */
for (const key of [
  'AT_API_KEY', 'AT_USERNAME', 'AT_SENDER_ID', 'GROQ_API_KEY', 'ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'AI_PROVIDER', 'TRANSCRIBE_PROVIDER',
  'ENCRYPTION_KEY', 'HASH_PEPPER', 'DASHBOARD_TOKEN', 'WEBHOOK_SECRET', 'PUBLIC_BASE_URL', 'DB_TYPE', 'DATABASE_URL',
  'COUNSELLOR_NUMBERS', 'CALL_MAX_QUESTIONS', 'RECORDING_URL_HOSTS', 'ESCALATION_MINUTES', 'RETENTION_DAYS', 'RETENTION_OPEN_DAYS',
  'RATE_LIMIT_REPORTS_PER_HOUR', 'RATE_LIMIT_INFO_PER_HOUR', 'RATE_LIMIT_REPLIES_PER_HOUR', 'AI_MAX_CALLS_PER_MINUTE',
  'API_RATE_LIMIT_PER_MINUTE', 'WEBHOOK_RATE_LIMIT_PER_MINUTE', 'DEMO_RESPONDER_PHONE', 'TIER2_RESPONDER_PHONE',
]) delete process.env[key];
process.env.NODE_ENV = 'test';
process.env.SQLITE_PATH = ':memory:';
