import { Injectable, Logger } from '@nestjs/common';
import { buildTriageUserMessage, TRIAGE_SYSTEM_PROMPT } from './prompts';
import { normalizeTriage, rulesTriage, silentTriage, structuredTriage } from './rules';
import { TriageInput, TriageResult } from './triage.types';

/**
 * AI structures, humans decide. The model turns a raw narrative (voice transcript or SMS,
 * in English/Kiswahili/Sheng) into the responder-facing structure. Survivor-facing text is
 * never generated by the model: it always comes from vetted templates (src/i18n).
 */
@Injectable()
export class TriageService {
  private readonly logger = new Logger(TriageService.name);

  get provider(): string {
    const p = (process.env.AI_PROVIDER || '').toLowerCase();
    if (p) return p;
    return process.env.ANTHROPIC_API_KEY ? 'anthropic' : 'rules';
  }

  async triage(input: TriageInput): Promise<TriageResult> {
    const floor = rulesTriage(input);
    if (this.provider !== 'anthropic' || !input.text) return floor;
    try {
      const raw = await this.callAnthropic(input);
      return normalizeTriage(raw, input, floor);
    } catch (e) {
      this.logger.warn(`AI triage failed (${(e as Error)?.message || e}); falling back to rules-based triage`);
      return floor;
    }
  }

  structured(input: TriageInput): TriageResult { return structuredTriage(input); }
  silent(input: TriageInput): TriageResult { return silentTriage(input); }

  private async callAnthropic(input: TriageInput): Promise<any> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), Number(process.env.AI_TIMEOUT_MS || 12000));
    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        signal: controller.signal,
        headers: {
          'content-type': 'application/json',
          'x-api-key': process.env.ANTHROPIC_API_KEY,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model: process.env.ANTHROPIC_MODEL || 'claude-sonnet-5',
          max_tokens: 900,
          system: TRIAGE_SYSTEM_PROMPT,
          messages: [{ role: 'user', content: buildTriageUserMessage(input) }],
        }),
      });
      if (!res.ok) throw new Error(`Anthropic API ${res.status}: ${(await res.text()).slice(0, 200)}`);
      const data: any = await res.json();
      const text = (data.content || []).filter((b: any) => b.type === 'text').map((b: any) => b.text).join('\n');
      return parseJsonObject(text);
    } finally {
      clearTimeout(timer);
    }
  }
}

export function parseJsonObject(text: string): any {
  const cleaned = text.replace(/```json|```/g, '').trim();
  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  if (start < 0 || end < 0) throw new Error('No JSON object in model output');
  return JSON.parse(cleaned.slice(start, end + 1));
}
