import { MigrationInterface, QueryRunner } from "typeorm";

/** Baseline PostgreSQL schema. Generated by `npm run migration:generate`; later changes get their own migration. */
export class InitialSchema1789659782752 implements MigrationInterface {
    name = 'InitialSchema1789659782752'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "responders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "organisation" character varying NOT NULL, "phone" character varying NOT NULL, "tier" integer NOT NULL DEFAULT '1', "wards" text NOT NULL, "languages" text NOT NULL, "verifiedBy" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_60c78d4e2644b8713884bcd6072" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ref" character varying NOT NULL, "channel" character varying NOT NULL, "language" character varying NOT NULL DEFAULT 'en', "phoneEnc" text, "phoneHash" character varying, "phoneMasked" character varying, "safeToContact" boolean NOT NULL DEFAULT false, "consentSharePolice" boolean NOT NULL DEFAULT false, "ward" character varying, "narrativeEnc" text, "recordingUrlEnc" text, "triage" json, "pathway" json, "urgency" character varying NOT NULL DEFAULT 'medium', "status" character varying NOT NULL DEFAULT 'OPEN', "acknowledgedBy" character varying, "acknowledgedAt" TIMESTAMP, "escalateAt" TIMESTAMP, "callbackWindow" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "acknowledgedById" uuid, CONSTRAINT "UQ_f24d2334f494ceff5688fe84cc6" UNIQUE ("ref"), CONSTRAINT "PK_264acb3048c240fb89aa34626db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cases_phoneHash" ON "cases" ("phoneHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_cases_status_escalateAt" ON "cases" ("status", "escalateAt") `);
        await queryRunner.query(`CREATE TABLE "case_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "type" character varying NOT NULL, "actor" character varying, "detail" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_61f203ee26b76c6438bbcc7bde6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_case_events_caseId" ON "case_events" ("caseId") `);
        await queryRunner.query(`CREATE TABLE "resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying NOT NULL, "name" character varying NOT NULL, "coverage" character varying NOT NULL DEFAULT 'national', "phone" character varying, "hours" character varying, "free" boolean NOT NULL DEFAULT true, "noteEn" text, "noteSw" text, "verified" boolean NOT NULL DEFAULT false, "source" character varying, CONSTRAINT "PK_632484ab9dff41bba94f9b7c85e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "cases" ADD CONSTRAINT "FK_2dcf06c01e20aa9b20836eaa944" FOREIGN KEY ("acknowledgedById") REFERENCES "responders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case_events" ADD CONSTRAINT "FK_7f6273ba7c5ebf8163a8dfc7892" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "case_events" DROP CONSTRAINT "FK_7f6273ba7c5ebf8163a8dfc7892"`);
        await queryRunner.query(`ALTER TABLE "cases" DROP CONSTRAINT "FK_2dcf06c01e20aa9b20836eaa944"`);
        await queryRunner.query(`DROP TABLE "resources"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_case_events_caseId"`);
        await queryRunner.query(`DROP TABLE "case_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cases_status_escalateAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cases_phoneHash"`);
        await queryRunner.query(`DROP TABLE "cases"`);
        await queryRunner.query(`DROP TABLE "responders"`);
    }

}
